version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: matchdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d matchdb" ]
      interval: 10s
      retries: 5

  app:
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/matchdb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8080:8080"

volumes:
  pgdata:
